apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: default
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: loadgenerator
        env:
        - name: LOG_LEVEL
          value: "debug"
