apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
  namespace: default
spec:
  selector:
    matchLabels:
      app: balancereader
  template: 
    spec: 
      containers:
      - name: balancereader
        image: gcr.io/megan-streams/cymbal-bank/release/balancereader:08ba3e2
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"
