apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  namespace: default
spec:
  selector:
    matchLabels:
      app: contacts
  template: 
    spec: 
      containers:
      - name: contacts
        image: gcr.io/megan-streams/cymbal-bank/release/contacts:737f7e6
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"
