apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: default
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: gcr.io/megan-streams/cymbal-bank/release/loadgenerator:08ba3e2
        env:
        - name: LOG_LEVEL
          value: "info"
